import com.pranvir.fizz.*
import java.io.File
import java.util.concurrent.Executors
import java.util.concurrent.Future

object Calibrate {
    @JvmStatic fun main(a: Array<String>) {
        val t0 = System.currentTimeMillis()
        val ex = Executors.newFixedThreadPool(2)
        val futs = ArrayList<Future<IntArray>>()
        for (n in 0 until Reels.TOTAL) futs.add(ex.submit<IntArray> { Bot.calibrate(n) { System.err.println(it) } })
        val rows = futs.mapIndexed { n, f -> f.get().also { r -> println("L$n ${Goal.TITLE[Reels.goal(n)]}: ${r.toList()}") } }
        ex.shutdown()
        val sb = StringBuilder()
        sb.append("package com.pranvir.fizz\n\n/** Generated by jvmtest/Calibrate.kt — do not edit by hand. [variant, shots, interval, s2, s3] per level. */\nobject LevelData {\n    val D = intArrayOf(\n")
        for ((n, r) in rows.withIndex()) sb.append("        ").append(r.joinToString(", ")).append(if (n < rows.size - 1) "," else "").append(" // L${n + 1}\n")
        sb.append("    )\n}\n")
        File("/home/claude/fizz/src/com/pranvir/fizz/LevelData.kt").writeText(sb.toString())
        println("CALIBRATED in ${(System.currentTimeMillis() - t0) / 1000}s")
    }
}
