import com.pranvir.fizz.*
import java.io.File
import java.util.concurrent.Executors

/** Loosens shot budgets on the levels a so-so player clears less than half the time. */
object Soften {
    @JvmStatic fun main(a: Array<String>) {
        val d = LevelData.D.copyOf()
        val ex = Executors.newFixedThreadPool(2)
        val futs = (0 until Reels.TOTAL).map { n -> ex.submit<IntArray> {
            val row = intArrayOf(d[n * 5], d[n * 5 + 1], d[n * 5 + 2], d[n * 5 + 3], d[n * 5 + 4])
            val spec = LevelSpec(n)
            if (!spec.limited) return@submit row
            var shots = row[1]
            for (it in 0 until 5) {
                spec.shots = shots
                val wins = (0 until 8).count { k -> Bot.play(spec, 31000L + n * 7 + k * 131, 0.55f).won }
                if (wins >= 4) break
                shots = (shots * 1.12f).toInt() + 1
            }
            if (shots != row[1]) {
                // star scores scale with the extra encore shots
                val extra = (shots - row[1]) * Match.ENCORE_SHOT
                row[3] += extra / 2; row[4] += extra / 2
                println("L${n + 1}: ${row[1]} -> $shots")
                row[1] = shots
            }
            row
        } }
        val rows = futs.map { it.get() }
        ex.shutdown()
        val sb = StringBuilder()
        sb.append("package com.pranvir.fizz\n\n/** Generated by jvmtest/Calibrate.kt (+ Soften.kt) — do not edit by hand. [variant, shots or par, interval, s2, s3] per level. */\nobject LevelData {\n    val D = intArrayOf(\n")
        for ((n, r) in rows.withIndex()) sb.append("        ").append(r.joinToString(", ")).append(if (n < rows.size - 1) "," else "").append(" // L${n + 1}\n")
        sb.append("    )\n}\n")
        File("/home/claude/fizz/src/com/pranvir/fizz/LevelData.kt").writeText(sb.toString())
        println("SOFTENED")
    }
}
